import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "t-shirt-with-tape-details",
    name: "T-shirt with Tape Details",
    price: 120,
    rating: 4.5,
    reviewCount: 451,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg1-DzpZ5m2Z-DuWpfth8t1oEkOTXmyBSDeXAefjy5U.png",
    colors: ["black", "white", "blue", "red", "green"],
    sizes: ["S", "M", "L", "XL"],
    category: "t-shirts",
    description: "A comfortable t-shirt with unique tape details that add a modern touch to a classic design.",
  },
  {
    id: "sleeve-striped-t-shirt",
    name: "Sleeve Striped T-shirt",
    price: 130,
    originalPrice: 185,
    discount: 30,
    rating: 4.5,
    reviewCount: 325,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg4-CJLzc85S-e1BQ9sPfBeO6yT1Yuyx7kkpgoQq9r5.png",
    colors: ["orange", "black", "blue"],
    sizes: ["S", "M", "L", "XL"],
    category: "t-shirts",
    description: "A stylish striped t-shirt with contrasting sleeves for a bold, sporty look.",
  },
  {
    id: "checkered-shirt",
    name: "Checkered Shirt",
    price: 180,
    rating: 4.5,
    reviewCount: 215,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg3-WGABrDuQ-RHj4ldmFpsjzWc9j9zKugOMBVOM5Ex.png",
    colors: ["red", "blue", "green"],
    sizes: ["S", "M", "L", "XL"],
    category: "shirts",
    description: "A classic checkered shirt that's perfect for casual outings or semi-formal occasions.",
  },
  {
    id: "skinny-fit-jeans",
    name: "Skinny Fit Jeans",
    price: 240,
    originalPrice: 300,
    discount: 20,
    rating: 3.5,
    reviewCount: 178,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg2-B2LMqJpm%20%281%29-guyGpQudiQI7y9W7wDzjKbhntQSpZx.png",
    colors: ["blue", "black", "gray"],
    sizes: ["28", "30", "32", "34", "36"],
    category: "jeans",
    description: "Modern skinny fit jeans that offer both style and comfort for everyday wear.",
  },
  {
    id: "vertical-striped-shirt",
    name: "Vertical Striped Shirt",
    price: 212,
    originalPrice: 265,
    discount: 20,
    rating: 5,
    reviewCount: 92,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg5-Cnq8tfsK%20%281%29-CeLLGLSrUAWlO4J4NiwIHgiWTn0U5E.png",
    colors: ["green", "blue", "white"],
    sizes: ["S", "M", "L", "XL"],
    category: "shirts",
    description: "An elegant vertical striped shirt that adds sophistication to your wardrobe.",
  },
  {
    id: "courage-graphic-t-shirt",
    name: "Courage Graphic T-shirt",
    price: 145,
    rating: 4,
    reviewCount: 156,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg6-DjL6382h-4LnlCiNBp0SUPZzIx5aOnOvaY12MjX.png",
    colors: ["orange", "white", "black"],
    sizes: ["S", "M", "L", "XL"],
    category: "t-shirts",
    description: "Express yourself with this bold graphic t-shirt featuring an inspiring 'Courage' design.",
  },
  {
    id: "one-life-graphic-t-shirt",
    name: "One Life Graphic T-shirt",
    price: 260,
    originalPrice: 325,
    discount: 20,
    rating: 4.5,
    reviewCount: 203,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg9-B5NFyH7l-txlmyO6aCflqJBnoxTnU8W4MyzHlML.png",
    colors: ["olive", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    category: "t-shirts",
    description: "A premium graphic t-shirt with a meaningful 'One Life' message and distressed print.",
  },
  {
    id: "polo-with-contrast-trims",
    name: "Polo with Contrast Trims",
    price: 212,
    originalPrice: 265,
    discount: 20,
    rating: 4,
    reviewCount: 87,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg11-DlxNjezl-ivLLfyTTo6n1auhiBx1t1IoXVcW5j2.png",
    colors: ["blue", "red", "black", "white"],
    sizes: ["S", "M", "L", "XL"],
    category: "polos",
    description: "A classic polo shirt with modern contrast trims for a sophisticated casual look.",
  },
  {
    id: "polo-with-tipping-details",
    name: "Polo with Tipping Details",
    price: 180,
    rating: 4.5,
    reviewCount: 124,
    image: "/placeholder.svg?height=300&width=300",
    colors: ["pink", "blue", "white", "black"],
    sizes: ["S", "M", "L", "XL"],
    category: "polos",
    description: "An elegant polo shirt with subtle tipping details that add a touch of refinement.",
  },
  {
    id: "black-striped-t-shirt",
    name: "Black Striped T-shirt",
    price: 120,
    originalPrice: 150,
    discount: 20,
    rating: 5,
    reviewCount: 76,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg14-B6MnPpY1-0rLt5lAzBCVzeELQwmoCzHmuBXyAsE.png",
    colors: ["black", "white"],
    sizes: ["S", "M", "L", "XL"],
    category: "t-shirts",
    description: "A sleek black and white striped t-shirt with a modern fit and premium fabric.",
  },
  {
    id: "faded-skinny-jeans",
    name: "Faded Skinny Jeans",
    price: 210,
    rating: 4.5,
    reviewCount: 183,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg2-B2LMqJpm-9FcMBnZXtDMq3vCIYpvYc2nSfDMhty.png",
    colors: ["blue", "black"],
    sizes: ["28", "30", "32", "34", "36"],
    category: "jeans",
    description: "Stylish faded skinny jeans with a comfortable stretch fabric for all-day wear.",
  },
  {
    id: "loose-fit-bermuda-shorts",
    name: "Loose Fit Bermuda Shorts",
    price: 240,
    originalPrice: 300,
    discount: 20,
    rating: 4.5,
    reviewCount: 97,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Svg7-CY4wcGfF-6qkH9m6u4FhvWfPdFgXL4iVQ8LbUic.png",
    colors: ["blue", "black", "beige"],
    sizes: ["28", "30", "32", "34", "36"],
    category: "shorts",
    description: "Comfortable loose fit bermuda shorts perfect for casual summer days.",
  },
  {
    id: "relaxed-fit-twill-utility-shorts",
    name: "Relaxed Fit Twill Utility Shorts",
    price: 260,
    originalPrice: 290,
    discount: 10,
    rating: 5,
    reviewCount: 64,
    image: "/placeholder.svg?height=300&width=300",
    colors: ["beige", "olive", "black"],
    sizes: ["28", "30", "32", "34", "36"],
    category: "shorts",
    description: "Durable twill utility shorts with a relaxed fit and practical pockets.",
  },
  {
    id: "gradient-graphic-t-shirt",
    name: "Gradient Graphic T-shirt",
    price: 145,
    rating: 3.5,
    reviewCount: 112,
    image: "/placeholder.svg?height=300&width=300",
    colors: ["white", "black"],
    sizes: ["S", "M", "L", "XL"],
    category: "t-shirts",
    description: "A unique t-shirt featuring a vibrant gradient graphic design that stands out.",
  },
]
